name: WSB Github Workflow
on: [push]
jobs:
  docker_python_versions:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check docker & python versions
        uses: actions/checkout@v3
  pylint_check:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - run: pylint app.py
      - name: Check app.py pylint
        uses: actions/checkout@v3
