name: WSB Github Workflow
on: [push]
jobs:
  docker_python_versions:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check docker & python versions
        uses: actions/checkout@v3
  pylint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout@v3
        uses: actions/checkout@v3
      - name: Install pylint module
        run: pip install pylint
      - name: Pylint test app.py
        run: pylint app.py
  build_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Use checkout@v3
          uses: actions/checkout@v3
        - name: Install docker
        - run: pip install docker
        - name: Build docker image
        - run: docker build --tag test-flask-app .
