name: WSB Github Workflow
on: [push]
jobs:
  docker_python_versions:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check docker & python versions
        uses: actions/checkout@v3
  pylint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout@v3
        uses: actions/checkout@v3
      - name: Install pylint module
        run: pip install pylint
      - name: Pylint test app.py
        run: pylint app.py
